name: Update AUR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-aur:
    runs-on: ubuntu-latest

    container:
      image: archlinux

    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm wget jq

      - name: Download Package
        run: |
          set -x
          latest_version=$(curl -s https://api.github.com/repos/NovaPlay-Gaming/novaplay-desktop-client/releases/latest | jq -r .tag_name)
          version_without_v=$(echo $latest_version | cut -c 2-)
          wget https://github.com/NovaPlay-Gaming/novaplay-desktop-client/releases/download/${latest_version}/novaplay-${version_without_v}.pacman -O novaplay.pacman
          set +x
        if: ${{ success() }}

      - name: Update PKGBUILD
        run: |
          set -x
          latest_version=$(curl -s https://api.github.com/repos/NovaPlay-Gaming/novaplay-desktop-client/releases/latest | jq -r .tag_name)
          pkgver=${latest_version#v}
          pkgrel=1
          url="https://github.com/NovaPlay-Gaming/novaplay-desktop-client"
          _filename=novaplay-${pkgver}.pacman
          source=("$url/releases/download/$latest_version/$_filename")
          md5sums=($(md5sum novaplay.pacman | cut -d' ' -f1))

          cat <<EOF > PKGBUILD
          # Maintainer: flaviofearn <flavioislima@gmail.com>
          # Maintainer: blingus <brett@novaplay.xyz>

          pkgname=novaplay
          pkgver=$pkgver
          pkgrel=$pkgrel
          pkgdesc="An open source Web3 gaming platform."
          arch=('x86_64')
          url="$url"
          license=('GPL3')
          depends=('gawk')
          _filename=$_filename
          source=("$source")
          noextract=("$_filename")
          md5sums=(${md5sums[@]})
          options=(!strip)

          package() {
            tar -xJv -C "\$pkgdir" -f "\$srcdir/\$_filename" usr opt
            mkdir "\$pkgdir/usr/bin"
            ln -s "/opt/NovaPlay/novaplay" "\$pkgdir/usr/bin/novaplay"
          }

          # vim:set ts=2 sw=2 et: syntax=sh

          EOF
          cat PKGBUILD
              set +x
        if: ${{ success() }}

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.2
        with:
          pkgname: novaplay
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
